name: Test

on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    test:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
        steps:
            - uses: actions/checkout@v6
              with:
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

            - uses: actions/setup-node@v6
              with:
                  node-version: 18
                  cache: npm
                  registry-url: https://registry.npmjs.org/

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm test

            - name: Lint
              run: npm run lint
